name: SAST and Image Scan

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
  
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker Daemon (if needed)
        run: |
          echo '{ "log-driver": "json-file", "log-level": "warn" }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Check Docker Status
        run: sudo systemctl status docker || sudo systemctl start docker

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Install Docker Scout CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Authenticate with Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Run Docker Scout Quickview
        run: docker scout quickview myapp:latest

      - name: Run Docker Scout CVE Scan
        run: docker scout cves myapp:latest
